### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by monochromec** [Krillsson/sys-API#117]
As the wiki seems to be only sparsely populated: Where would I find an specification of the REST API (including a list of valid endpoints, etc)?

**Comment by Krillsson** [comment]
currently, there is none. Would you consider using the GraphQL API instead? You can browse through the schema _.graphqls_ files here: https://github.com/Krillsson/sys-API/tree/master/server/src/main/resources. Start with the system.graphqls and go from there.

[Apollo Blog: GraphQL vs REST](https://www.apollographql.com/blog/graphql/basics/graphql-vs-rest/)

**Comment by Krillsson** [comment]
If you insist on REST. The new GitHub code navigation works well with browsing the resources; https://github.com/Krillsson/sys-API/tree/master/server/src/main/java/com/krillsson/sysapi/rest

**Comment by monochromec** [comment]
Thanks for the quick reaction. Unfortunately I don't have the time for a detailed code analysis. 

I assume there would be a greater uptake of this CB with a proper documentation in place (eg. similar to glances, etc.).
