### ISSUE TITLE
Running with docker

### ISSUE THREAD

**Issue by cookins** [Krillsson/sys-API#118]
Hey. So i found app in play market and bought it. Now I'm trying to set docker container and it started and running, but it not opens any ports, so Android app can't connect. I tried to - uncomment `ports:` and `- "8080:8080"`, but i getting error `ERROR: for sys-api  "host" network_mode is incompatible with port_bindings`. I think, you need make better instruction how to setup it in all situations, with examples, please. Also, there error in command wrote in example line, how to set up container - `docker compose`, while it supposed to be `docker-compose`. Hopefully, i will get answer shortly, if you can. Ty

**Comment by Krillsson** [comment]
Thanks for the feedback @cookins.

I am working on improving documentation. Can you try this page [https://monitee.app/connect-app-to-server/](https://monitee.app/connect-app-to-server/) ?

host networking don't need port bindings. You can leave the ports commented out.

Let me know how it goes

**Comment by Krillsson** [comment]
[See this about "docker compose" vs "docker-compose"](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose)

**Comment by Krillsson** [comment]
What error did it give you?

**Comment by cookins** [comment]
> What error did it give you?
```
sudo docker compose -f docker-compose.yml up
unknown shorthand flag: 'f' in -f
```
but if `sudo docker-compose -f docker-compose.yml up` all went fine

**Comment by cookins** [comment]
> Thanks for the feedback @cookins.
> 
> I am working on improving documentation. Can you try this page https://monitee.app/connect-app-to-server/ ?
> 
> host networking don't need port bindings. You can leave the ports commented out.
> 
> Let me know how it goes

so i checked that instruction.
still container running from root, but not listen on any 8080, 8443... i made rule with `ufw allow 8443` (only), and it created rule. after restart that rule was still exist. and again - nothing listens on that ports.. so i cant connect with android.
what exactly i need to change in config file, except login and pass?

**Comment by Krillsson** [comment]
No worries.

Have you verified that the server was started. Like in the bottom of this article: https://monitee.app/docker-compose/

Is the server on your local network or internet?

**Comment by cookins** [comment]
> Is the server on your local network or internet?
its remote VPS. and lol, i think i figured, that i dont have java installed, even. i totally just noticed, that script written on java.
`Command `java` not found, but can be installed with..` :D

**Comment by Krillsson** [comment]
If you are running inside docker you don't need java.

If you start the server outside of docker, then yes. You need java.

There is instructions on how to install java here.

https://monitee.app/get-going-with-sys-api/

However, I recommend to continue using docker. Since that will make it easier to upgrade the server when there is new releases.

**Comment by cookins** [comment]
I guess, installing java not helped, indeed.
![IMG_20230906_180528.jpg](https://github.com/Krillsson/sys-API/assets/7893051/d694d83c-48a7-4845-8b52-9432bb1e001f)

![IMG_20230906_180450.jpg](https://github.com/Krillsson/sys-API/assets/7893051/856e63c9-2e40-4ee4-a6d7-05931ed0363c)

![IMG_20230906_180502.jpg](https://github.com/Krillsson/sys-API/assets/7893051/ec008ae4-a6df-4bc3-965c-87a8d52177fc)

Running as root... What could it be?

**Comment by Krillsson** [comment]
```yaml
volumes: 
       - /usr/local/bin/monitee/data:/data 
       - /usr/local/bin/monitee/config:/config
```

Change docker-compose.yml so it says like above.

Then re-create container using

`sudo docker compose up --force-recreate`

**Comment by Krillsson** [comment]
> > It started, but now it can't find the configuration file. You probably need to edit the volume/folder bindings.
> > 
> > ```yaml
> > volumes: 
> >      - /usr/local/bin/monitee/data:/data 
> >      - /usr/local/bin/monitee/config:/config
> 
> Sorry for trouble, but:
> `root@tgbot:/usr/local/bin/monitee# docker-compose up --force-recreate sys-api
> 
> ERROR: yaml.parser.ParserError: while parsing a block collection
>   in "./docker-compose.yml", line 34, column 6
> expected <block end>, but found '<block sequence start>'
> 
>   in "./docker-compose.yml", line 37, column 7`
> ![IMG_20230906_190951.jpg](https://github.com/Krillsson/sys-API/assets/7893051/0924b342-b290-4ed3-927a-b8c45585e796)
> 
> 

Yes, yaml files need to have correct amount of spaces.

Put spaces infront of "-" so they line up with lines above.

**Comment by cookins** [comment]
It getting even more complicated:
https://pastebin.com/LKEWTm8f
It's long, so i better post it in pastebin. I think its related to 8081 port, but what it have to do with 8080 or 8443?
Ty for assistance

**Comment by Krillsson** [comment]
> It getting even more complicated:
> https://pastebin.com/LKEWTm8f
> It's long, so i better post it in pastebin. I think its related to 8081 port, but what it have to do with 8080 or 8443? But this time, all composing passed. Btw, special signs in password field, in config - making error.
> Ty for assistance

Ah, admin port is still active. I need to change that in the example config

Can you try replacing line

`adminContextPath: `

With

`adminConnectors: []`

This disables admin API (not used by Monitee)

**Comment by cookins** [comment]
> try replacing line\n\nadminContextPath:\n\nWith\n\nadminConnectors: []

That helped. Now it's working and all fine. I can see all data in android app. Thanks!
In case, you interesting, how it built successfully, terminal log: https://pastebin.com/i4EcnZjz
Cheers

**Comment by Krillsson** [comment]
Great job 💪🏻

Let me know if you have any ideas for features.
