### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cookins** [Krillsson/sys-API#122]
Hey.
So i got feature suggestion. There some services list, connections with ip, etc. I think, it can be more cool, in android app, if you able to tap and hold, to copy - service name, remote ip connections, other things in other lists. Could be handy.
![IMG_20230906_220557.jpg](https://github.com/Krillsson/sys-API/assets/7893051/5beaa4f0-2cc6-4329-a20d-a09871dd36e0)

**Comment by Krillsson** [comment]
Thanks for the suggestion. I documented it in the issue tracker for Monitee: [Share sheet with info about entities](https://github.com/Krillsson/moniteeapp/issues/3)
