### ISSUE TITLE
Cursor background 

### ISSUE THREAD

**Issue by cookins** [Krillsson/sys-API#123]
When i trying to edit server IP, my cursor's, and clear button, background - not transparent. I only saw it in server editing screen, for now:
![IMG_20230913_112757.jpg](https://github.com/Krillsson/sys-API/assets/7893051/7480f95c-409b-444e-a8e1-fd9ad68c2c5b)

**Comment by Krillsson** [comment]
oh, this isn't any good. I'll take a look 👍🏻
