### ISSUE TITLE
Podman management support

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Krillsson/sys-API#125]
As the title said.

**Comment by Krillsson** [comment]
Give a thumbs up to the original comment if you want this feature.

If there is a significant interest in supporting this I may consider implementing it

**Comment by Krillsson** [comment]
Something you can try:

Podman appears to have a compatibility layer with docker REST-API which sys-API uses.

If you are running sys-API in a container, try replacing the host part of the docker socket volume binding with podmans rootful socket `/run/podman/podman.sock`

In standalone mode you can try doing the same with a docker-java config .properties file and only defining DOCKER_HOST with the podman socket as per their documentation https://github.com/docker-java/docker-java/blob/main/docs/getting_started.md

**Comment by wolf-yuan-6115** [comment]
> Something you can try:
> 
> Podman appears to have a compatibility layer with docker REST-API which sys-API uses.
> 
> If you are running sys-API in a container, try replacing the host part of the docker socket volume binding with podmans rootful socket `/run/podman/podman.sock`
> 
> In standalone mode you can try doing the same with a docker-java config .properties file and only defining DOCKER_HOST with the podman socket as per their documentation https://github.com/docker-java/docker-java/blob/main/docs/getting_started.md

Sure, I will try it out when I'm free

**Comment by Krillsson** [comment]
@wolf-yuan-6115 try the latest release 0.19.2. I got it working on my machine. Had to spin up a new debian server VM and install podman from there, since I run docker on my servers.

depending on your setup:

sys-API from the docker image

- keep the volume binding as instructed earlier

sys-API in standalone mode

- I added support for manually overriding the docker host from the configuration file. Configure it as such:

```yaml

docker:
  enabled: true
  host: unix:///run/podman/podman.sock
```

**Comment by Krillsson** [comment]
@wolf-yuan-6115 did you get it working?

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 did you get it working?

I haven't tested it yet, I'll test when I'm free.

**Comment by wolf-yuan-6115** [comment]
Well, that's weird:

```
ERROR [2023-12-06 02:04:46,539] graphql.kickstart.execution.error.DefaultGraphQLErrorHandler: Error executing query Exception while fetching data (/docker/containers) : networks must not be null
! java.lang.NullPointerException: networks must not be null
! at com.krillsson.sysapi.docker.ExtensionsKt.asNetworkSettings(Extensions.kt:71)
! at com.krillsson.sysapi.docker.ExtensionsKt.asContainer(Extensions.kt:50)
! at com.krillsson.sysapi.docker.DockerClient.listContainersInternal(DockerClient.kt:142)
! at com.krillsson.sysapi.docker.DockerClient.containersCache$lambda$2(DockerClient.kt:63)
! at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:262)
! at com.krillsson.sysapi.docker.DockerClient.listContainers(DockerClient.kt:88)
! at com.krillsson.sysapi.graphql.QueryResolver$DockerResolver.containers(QueryResolver.kt:172)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
! at graphql.kickstart.tools.resolver.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:280)
! at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:309)
! at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:286)
! at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:212)
! at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
! at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:680)
! at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:472)
! at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:422)
! at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:214)
! at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
! at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
! at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
! at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:213)
! at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
! at graphql.execution.Execution.executeOperation(Execution.java:156)
! at graphql.execution.Execution.execute(Execution.java:102)
! at graphql.GraphQL.execute(GraphQL.java:557)
! at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:476)
! at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
! at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
! at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:471)
! at graphql.GraphQL.executeAsync(GraphQL.java:439)
! at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:37)
! at graphql.kickstart.execution.GraphQLInvoker.execute(GraphQLInvoker.java:28)
! at graphql.kickstart.servlet.HttpRequestInvokerImpl.invoke(HttpRequestInvokerImpl.java:200)
! at graphql.kickstart.servlet.HttpRequestInvokerImpl.lambda$invokeAndHandleAsync$2(HttpRequestInvokerImpl.java:84)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by wolf-yuan-6115** [comment]
By the way, I'm running podman in rootless mode which doesn't seem to have a network switch...?

**Comment by Krillsson** [comment]
ah okay, let me try with rootless mode on my end. I can quick fix the error but probably it will error out in more places after that

**Comment by Krillsson** [comment]
It turned out to be only networks that was erroring.

For future reference I followed the [rootless guide](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md) and then [socket activation](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md) to activate the API socket for my non-root user.

**Comment by Krillsson** [comment]
Let's try again with [0.19.3](https://github.com/Krillsson/sys-API/releases/tag/0.19.3) @wolf-yuan-6115

**Comment by wolf-yuan-6115** [comment]
> Let's try again with [0.19.3](https://github.com/Krillsson/sys-API/releases/tag/0.19.3) @wolf-yuan-6115 

Yup, working now:

![Screenshot_20231211-062929.png](https://github.com/Krillsson/sys-API/assets/58245644/722a02bc-d1ae-4d4a-8606-0c3c74af2b91)

![Screenshot_20231211-063042.png](https://github.com/Krillsson/sys-API/assets/58245644/894a66f6-f5fc-4db1-b443-348e18227e3d)

**Comment by Krillsson** [comment]
thanks! 🙌🏻
