### ISSUE TITLE
Tutorial outdated

### ISSUE THREAD

**Issue by BalthasarBH** [Krillsson/sys-API#133]
Hey Krillsson!
Before you solve my problem.. The app is very nice :D
I've been looking for a tutorial for a really long time because your Youtube video is set to Unlisted. That was a shame and besides, you're showing an older version of the setup. That had made me a bit sad at first, where I didn't have a setup assistant in the app so I was left a bit alone. However, I managed to do it on my own after about 20 minutes on my own, but it would have been difficult for a fairly fresh one from the tech world. But it works now and I'm happy :D

***The blame for my bad English is Google Translate xD**

**Comment by Krillsson** [comment]
Hey. I agree, the YT tutorial is very outdated. I have made a new tutorial on the apps homepage: [https://monitee.app/get-started/](https://monitee.app/get-started/ ). 

It is shown inside the app when you press HELP from the Add server screen. Perhaps I need to make the tutorial even more noticeable.

Can you have a look at the new tutorial, would it have made your setup faster? And thanks, glad you like the app.

**Comment by BalthasarBH** [comment]
The tutorial is much better and understandable! It would be nice if the following things were mentioned, which Java version must be available and that the new users would get an insight into the topic of configuration. I disabled the following things to get it to work for me:
- systemDaemonServiceManagement
- docker
I didn't know if I should disable graphQLPlayGround too, I didn't change it and it worked!
It would be nice if this was also included in the tutorial, so to speak, for “new” users so that it works straight away!

**Comment by Krillsson** [comment]
Excellent feedback. I'm thinking, this could be solved by writing comments in the configuration file. That would be easier to maintain.
