### ISSUE TITLE
Add monitor for localhost webservers

### ISSUE THREAD

**Issue by adrianbolboceanu** [Krillsson/sys-API#140]
For example, I have web servers of Plex, qBittorrent and others running on my own server.
I would see it a simple monitor for eg. http://localhost:32400/ that looks for a HTTP 200 response.

**Comment by Krillsson** [comment]
@adrianbolboceanu your request have now been fulfilled. Enjoy 🎉 

| List page | Server dashboard widget | Detailed page |
|--------|--------|--------|
| ![Image](https://github.com/Krillsson/sys-API/assets/2466419/96b796f3-1b15-49f5-a77c-5344d4624c9e) | ![Image](https://github.com/Krillsson/sys-API/assets/2466419/714150e4-7120-42d5-ace9-1505a76c117f)| ![Image](https://github.com/Krillsson/sys-API/assets/2466419/baeb9ffd-4131-4f18-b759-2422bbe1594f) |

**Comment by Krillsson** [comment]
Reopening for visibility...

**Comment by adrianbolboceanu** [comment]
Amazing, thank you!
