### ISSUE TITLE
Java version error

### ISSUE THREAD

**Issue by flying-pizza-69** [Krillsson/sys-API#143]
user@pi:~/monitee/sysapi-shadow-0.30.0 $ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Debian-1deb11u1, mixed mode, sharing)

user@pi:~/monitee/sysapi-shadow-0.30.0 $ ./run.sh
Error: LinkageError occurred while loading main class com.krillsson.sysapi.SysAPIApplicationKt
        java.lang.UnsupportedClassVersionError: com/krillsson/sysapi/SysAPIApplicationKt has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by Krillsson** [comment]
this is due to your version of java is older than what the new version of sys-API require (17 vs 21). I should have mentioned this in the release notes, sorry.

The new package in apt-get is called `openjdk-21-jdk`

**Comment by flying-pizza-69** [comment]
thanks, it works now. btw it would be great to have the ability to change the port number for sysapi graphql service.

**Comment by Krillsson** [comment]
You can change the port in the application.properties file inside the config directory.

**Comment by joenepraat** [comment]
> this is due to your version of java is older than what the new version of sys-API require (17 vs 21). I should have mentioned this in the release notes, sorry.
> 
> The new package in apt-get is called `openjdk-21-jdk`

The most recent version Debian 12 is openjdk-17-jdk.
