### ISSUE TITLE
"Notify on new ongoing event" meaning?

### ISSUE THREAD

**Issue by bhugh** [Krillsson/sys-API#154]
Under edit monitor for a webserver their is a toggle "Notify on new ongoing event". 

Can you explain this a little further?

**Comment by Krillsson** [comment]
The monitor part ties into the regular monitoring feature of the app. "Notify on new ongoing event" will send a local notification to your phone. If you leave this off, the event will just show up in the app

So in this case for a webserver, it will notify you when it has replied with something other than 200 or is down after the given delay
