### ISSUE TITLE
No support for raspberry pi: linux/armv7 yet?

### ISSUE THREAD

**Issue by ashishgupta250** [Krillsson/sys-API#165]
It always ends with: no matching manifest for linux/armv7 in the manifest list entries

**Comment by Krillsson** [comment]
There was no appropriate base image that had armv7 only arm64. I can check again. 

If you are running Raspbian or some other Debian based distro you can also try the .deb file

https://monitee.app/deb-package/

**Comment by Krillsson** [comment]
I have searched through the popular providers of base images for jdk builds (temurin, zulu, correto etc). None of them provided armv7 builds of java-21. So my hands are tied unfortunately.
