### ISSUE TITLE
Web Interface for sys-API

### ISSUE THREAD

**Issue by Rollbacke** [Krillsson/sys-API#167]
Hi,

sys-API and monitee are an amazing project.

Have you considered creating a web interface?
This would make the dashboard accessible from any device, not just from an Android/iOS phone.

Unfortunately, not being a developer, I can't help with its creation.

Regards,

**Comment by Rollbacke** [comment]
I don't know if it's a duplicate of #12.

**Comment by Krillsson** [comment]
This is a duplicate of #12 yes

To give you an answer: I currently do not have the capacity to develop and maintain two separate client applications for sys-API. That's why I added the [Help wanted] label to the original issue.

**Comment by Krillsson** [comment]
We can continue the discussion in #12
