### ISSUE TITLE
[feature request] ssh linux/macos console session 

### ISSUE THREAD

**Issue by philgood** [Krillsson/sys-API#19]
Is there anyway to incorporate a new tab as a ssh console session within the Monitee app? This would be super helpful for remote updates and administration of linux/macos server machines.

**Comment by Krillsson** [comment]
I'm sorry, but I've made an active decision not to implement anything like this. As the security implication is far too great.

Here's a nice app for SSH on android: https://play.google.com/store/apps/details?id=com.sonelli.juicessh
