### ISSUE TITLE
More bugs need fix!

### ISSUE THREAD

**Issue by Droid-MAX** [Krillsson/sys-API#31]
Graphql function is abnormal, monitee 0.4.0 version connects to latest sys-API server abnormally, prompting unauthenticated

**Comment by Droid-MAX** [comment]
My server is deployed on a VPS with a public IP, and I use curl command and app to access the sys-API application. The former is normal and the latter fails.

**Comment by Krillsson** [comment]
I am sorry for the issues you are experiencing. The sys-API server is still in it's early stages and unfortunately I have to make API-breaking changes.

The current version of the Monitee app is compatible with sys-API server version [0.11](https://github.com/Krillsson/sys-API/releases/tag/0.11)
