### ISSUE TITLE
Deprecate REST API

### ISSUE THREAD

**Issue by Krillsson** [Krillsson/sys-API#45]
It's not used by the new version of Monitee and it's difficult to maintain two separate implementations at the same time

Downvote this issue if you want to keep it.

**Comment by Droid-MAX** [comment]
Are there any new candidates?

**Comment by Krillsson** [comment]
Candidates for the app or the API?

**Comment by Krillsson** [comment]
> Are there any new candidates?

@Droid-MAX do you mean the app or the API?

**Comment by Droid-MAX** [comment]
APIs

**Comment by Krillsson** [comment]
sys-API supports [GraphQL](https://graphql.org/) since version 0.13. It's a bit like a REST API, but you can pick and choose what you want in the response.

If you are running 0.13 or later you can access [GraphQL Playground](https://github.com/graphql/graphql-playground) if you go to `http://<server-ip>:<port>` (http://127.0.0.1:8080/) if you are running the server locally with the default port

**Comment by Krillsson** [comment]
will keep REST api for now
