### ISSUE TITLE
Which version of jdk are you used？

### ISSUE THREAD

**Issue by Droid-MAX** [Krillsson/sys-API#48]
I got an error about JNI, and show Unsupported ClassVersionError, I use openjdk-8-jre currently.

**Comment by Droid-MAX** [comment]
![mmexport1620721269036](https://user-images.githubusercontent.com/12762435/117796168-65994180-b281-11eb-9b22-8cffbf341e8c.png)

**Comment by Krillsson** [comment]
@Droid-MAX the release no longer require a java version since it comes with an embedded openjdk 11.

But if you prefer to run it yourself, you can use Java 11 ☺️

**Comment by Krillsson** [comment]
Actually you are right. It doesn't run on any other platform than Mac OSX. Please wait while I fix it.

**Comment by Krillsson** [comment]
@Droid-MAX try [0.15.1](https://github.com/Krillsson/sys-API/releases/tag/0.15.1) instead

**Comment by Droid-MAX** [comment]
I just repack it, and running with no errors.
see [system-api](https://github.com/Droid-MAX/system-api)

**Comment by Krillsson** [comment]
ah, ok. Just so you know: 0.15.0 embeds a jre in the package. But your repack uses the systems jre. Which is fine, since the embedded one was only usable on OSX. So there's a lot of stuff in the installation that is just junk.

0.15.1 removes the embedded jre.

**Comment by Droid-MAX** [comment]
[system-api-0.15.1](https://github.com/Droid-MAX/system-api/releases/tag/0.15.1) Released！
