### ISSUE TITLE
Issue w/ android app

### ISSUE THREAD

**Issue by Chaprnks** [Krillsson/sys-API#53]
Address: CLEARTEXT communication to * not permitted (rest cuts off screen). I made sure to use the sys-api thats compatible with the app.

![Screenshot_20210821-193500](https://user-images.githubusercontent.com/6340970/130337410-7fa84503-18d6-4c2e-8571-808d016f7414.png)

**Comment by Krillsson** [comment]
@Chaprnks I just released sys-API 0.16.0 and Monitee 0.5.0 to open beta. Mind giving it another go?

**Comment by Chaprnks** [comment]
@Krillsson Works flawlessly now! Great job on the android app UI overhaul! :D


![monitee1](https://user-images.githubusercontent.com/6340970/135734069-f33ce27d-5124-4fc3-bc9f-f77cc927f0e6.png)
![monitee2](https://user-images.githubusercontent.com/6340970/135734071-a7f60b6a-bb92-456a-a1c4-fec72b6747d5.png)
![monitee3](https://user-images.githubusercontent.com/6340970/135734072-9eb4e7e5-93de-493f-ada3-5b6a02f8827c.png)

**Comment by Krillsson** [comment]
Thanks mate! Stay tuned for more features to the app 👍🏻
