### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Zorgordian-github** [Krillsson/sys-API#75]
Quite confused. Followed the instructions on the readme for installing on linux all I'm getting is permission denied when I try to run it. Ran it as root. Permission denied. Chown didn't work ensuring it was executable didn't work. It has an issue with running the server script. 

Any ideas?

**Comment by Zorgordian-github** [comment]
I was being an idiot. My bad.

**Comment by Droid-MAX** [comment]
Which Linux rev are you used?
if Debian based OS, then you can try this packages
https://github.com/Droid-MAX/system-api/releases/tag/0.17.2

**Comment by Krillsson** [comment]
Sorry for not replying @Zorgordian-github. I messed up my notifications for this repo somehow. Should be fixed now.

Let me know if you need further assistance.
