### ISSUE TITLE
Support for arm64 docker image

### ISSUE THREAD

**Issue by valentinbreiz** [Krillsson/sys-API#77]
sys-api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s

Can you please create a docker image with arm64 platform?

**Comment by Krillsson** [comment]
should be fairly easy to setup. [Example here](https://github.com/GoogleContainerTools/jib/issues/3686#issuecomment-1149758685).

It's also possible to run sys-API outside of docker. I am running it on my M1 with no issues while working on it.

**Comment by valentinbreiz** [comment]
I'm using docker and a raspberry pi 4

**Comment by Krillsson** [comment]
@valentinbreiz latest release 0.18.0 supports arm64. Give it a go 👍🏻

**Comment by valentinbreiz** [comment]
Thanks for your fast response! I indeed successfully built and deployed the docker image. But now I have an other problem. I can connect to my server using Monitee:

![photo_5819147805648861495_y](https://user-images.githubusercontent.com/18724279/226211396-4cfe7299-251c-40c2-a4d3-630832710d99.jpg)

But when I go the the details page it says the server is unreachable... 

![photo_5819147805648861494_y](https://user-images.githubusercontent.com/18724279/226211428-d087b6e3-d313-468a-9e70-4e6b08eb6007.jpg)

**Comment by Krillsson** [comment]
There must be something going wrong with the requests.

Can you press the send logs button from the About screen? It will open a pre-filled email. 

You can change the recipient to yourself if you want to remove something from the it before you send it.

**Comment by valentinbreiz** [comment]
Just send you the logs :)

**Comment by Krillsson** [comment]
It turned out I had made an subtle incompatible change in the API. Version 0.7.2 of Monitee that was published an hour ago fixes it

**Comment by valentinbreiz** [comment]
Awesome it's working now thanks

**Comment by Droid-MAX** [comment]
same issues, but I can not upgrade properly in China, can you send me the latest apk file?

**Comment by Krillsson** [comment]
Send me an email with through the "Request Support" option in the About screen of the app and we can sort it out mate.

**Comment by Droid-MAX** [comment]
well done, my proxy issues, but now I fixed and upgrade successful.
