### ISSUE TITLE
Feature request: Add load average

### ISSUE THREAD

**Issue by joenepraat** [Krillsson/sys-API#98]
Can you please add **load average**? As a number, but also as a graph. Thanks!

**Comment by Krillsson** [comment]
sys-API expose the 1 minute load average from [OSHI](https://github.com/oshi/oshi/blob/1b7949c5d367e8c95b43764405f0cffa99044782/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L161). This is not currently visualised in the app, but should be easy to add it. I'll take a look at it.

Then there's the 5 and 15 minute load average. This would require a new API and that would take a bit longer time, unfortunately.

**Comment by joenepraat** [comment]
I saw a load average under the CPU information page, although it misses a decimal separator. It would really be great if you can add this. Also on the servers overview. I normally use load average a lot on my VPS's.

**Comment by Krillsson** [comment]
I implemented this in #107 a couple of days ago. The app parts are to be implemented soon.

**Comment by joenepraat** [comment]
> I implemented this in #107 a couple of days ago. The app parts are to be implemented.

Great! Thanks a lot!

**Comment by joenepraat** [comment]
> @joenepraat your feature request is completely fulfilled now with the latest updates to the app. You can see how it looks on the "Main screens" and "Detailed metrics" sections on the screenshots page
> 
> https://monitee.app/screenshots/

Super! Thanks a lot!
